version: '3.8'

# .env로 키 관리 예정
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: springboot_db
      MYSQL_USER: spring_user
      MYSQL_PASSWORD: spring_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  spring-app:
    build: .
    container_name: spring-boot-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springboot_db
      SPRING_DATASOURCE_USERNAME: spring_user
      SPRING_DATASOURCE_PASSWORD: spring_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - spring-network

volumes:
  mysql_data:

networks:
  spring-network:
    driver: bridge